site_name: ${{values.app_name}}
site_description: 'Main documentation for the ${{values.app_name}}'
repo_url: https://github.com/salva-moyano/${{values.app_name}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
    - Getting started: 'index.md'